#
# just configuration.
#
# https://just.systems/man/en
#

# List recipes.
help:
	just --list

# Prepare environment.
prepare:
	# Install JavaScript dependencies.
	bun install

# Run static analysis (format, lint, type check).
analyze: prepare
	# Format.
	if [[ -z "${CI:-}" ]]; then treefmt; else treefmt --fail-on-change; fi
	# Lint JavaScript files.
	if [[ -z "${CI:-}" ]]; then oxlint --fix; else oxlint; fi
	# Type check JavaScript files.
	bun run tsc

# Synthesize templates.
synthesize: prepare
	# Remove build artifacts.
	rm -rf build
	# Synthesize templates.
	bun run cdktn synthesize --quiet

# Release build.
build: analyze synthesize
